message("qtconfig.cmake  ${CMAKE_CURRENT_LIST_DIR}")

function(find_qcatgrayquick_pack)
if(ARGV0)
    set(QCatGrayQuickPath ${ARGV0}/QCatGrayQt${QT_VERSION_MAJOR}Compat)
    if (CMAKE_BUILD_TYPE MATCHES "Release")
        set(QCatGrayQuickRes ${QCatGrayQuickPath}/QCatGrayQuick/QCatGrayQuick.qrc)
        set(QCatGrayQuickImport "qrc:/qcatgrayquick_plugins" )
        set(QCatGrayQuickImage "qrc:/QCatGrayQuick/Images/")
    else()
        set(QCatGrayQuickRes ${QCatGrayQuickPath}/QCatGrayQuick/QCatGrayQuick.qrc)
        set(QCatGrayQuickImport "file:///${QCatGrayQuickPath}")
        set(QCatGrayQuickImage "file:///${QCatGrayQuickPath}/QCatGrayQuick/Images/")
    endif()
    add_definitions(-DQCatGrayQuickRes="${QCatGrayQuickRes}")
    add_definitions(-DQCatGrayQuickImport="${QCatGrayQuickImport}")
    add_definitions(-DQCatGrayQuickImage="${QCatGrayQuickImage}")

    add_definitions(-DQCatGrayQuickImportPath="${QCatGrayQuickImport}")
    add_definitions(-DQCatGrayQuickImagePath="${QCatGrayQuickImage}")
    message("QML_IMPORT_PATH: $ENV{QML_IMPORT_PATH}")
    message("QML2_IMPORT_PATH: $ENV{QML2_IMPORT_PATH}")
    message("QML_DESIGNER_IMPORT_PATH: $ENV{QML_DESIGNER_IMPORT_PATH}")
    set(ENV{QML_IMPORT_PATH} ${QCatGrayQuickPath})
    set(ENV{QML2_IMPORT_PATH} ${QCatGrayQuickPath})
    set(ENV{QML_DESIGNER_IMPORT_PATH} "${QCatGrayQuickPath}")
endif(ARGV0)
endfunction(find_qcatgrayquick_pack)

